---
  - hosts: database
    become: true        # Execute as sudo
    tasks:  
      - name: Insatall MySQL server
        apt: name=mysql-server state=present update_cache=yes

      - name: Start MySql server
        service: name=mysql state=started enabled=yes

      - name: Ensure MySql listening in all ports
        listeninfile: dest=/etc/mysql/my.cnf regexp=^bind-address
                      line="bind-address = 0.0.0.0"
        notify: restart_mysql

    handlers:
      - name: restart_mysql
        service: name=mysql state=restart 