version: '3.9'

volumes:
  ansible:
     driver: local

networks:
  net:

services:
  app01:
    container_name: app01
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    expose:
      - "22"
    networks:
      - net
  app02:
    container_name: app02
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    expose:
      - "22"
    networks:
      - net
  lb01:
    container_name: lb01
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    expose:
      - "22"
    networks:
      - net
    ports:
      - "8080:80"
  db02:
    container_name: db02
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    expose:
      - "22"
    networks:
      - net

  


  