version: '3.9'

volumes:
  ansible:
     driver: local

networks:
  net:

services:
  amazonlinux-server: 
    container_name: amazonlinux-server
    # image: amazonlinux:2
    build:
      context: .
      dockerfile: Dockerfile.AWS
    volumes:
      - ~/.aws:/root/.aws
      - ./src:/ansible
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - net
  ubuntu-server:
    container_name: ubuntu-server
    image: ubuntu
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - net
  centos-server:
    container_name: centos-server
    image: centos
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - net
  