version: '3.9'

volumes:
  ansible:
     driver: local

networks:
  net:

services:
  # amazonlinux-server: 
  #   container_name: amazonlinux-server
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.AWS
  #   volumes:
  #     - ~/.aws:/root/.aws
  #     - ./src:/ansible
  #   ports:
  #     - "22"
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   networks:
  #     - net
  ubuntu-server-1:
    container_name: ubuntu-server-1
    build:
      context: .
      dockerfile: Dockerfile.Ubuntu
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - net
    expose:
      - "22"


  