---
# tasks file for apache2
- name: 1.0 -- Install apache2
  apt: name={{ item }} state=present update_cache=yes
  loop:
    - apache2
    - libapache2-mod-wsgi
    - python3-pip
    - python3-dev
    - python3-mysqldb
    - python3-virtualenv
    - build-essential
    - libssl-dev
    - libffi-dev

- name: 1.1 -- Start Service Apache2
  service: name=apache2 state=started enabled=yes

- name: 1.2 -- Ensure mod_wsgi enabled
  apache2_module: state=present name=wsgi 
  notify: restart_apache2

- name: 1.3 -- Copy demo app source
  copy: src=src/app/ dest=/var/www/app mode=0755
  notify: restart_apache2

- name: 1.4 -- Copy apache virtual host config
  copy: src=src/app.conf dest=/etc/apache2/sites-available mode=0755
  notify: restart_apache2

- name: 1.4.1 -- Copy apache virtual host config
  copy: src=src/app.wsgi dest=/var/www/app/ mode=0755
  notify: restart_apache2
  
- name: 1.5 -- Setup Python virtual environment
  pip: requirements=/var/www/app/requirements.txt virtualenv=/var/www/app/.venv
  notify: restart_apache2

- name: 1.6 -- Deactivate the default apache site
  file: path=/etc/apache2/sites-available/000-default.conf state=absent
  notify: restart_apache2

- name: 1.7 -- Activate app site
  file: src=/etc/apache2/sites-available/app.conf dest=/etc/apache2/sites-enabled/app.conf state=link
  notify: restart_apache2
        