- name: 1.0 -- Update and Upgrade
  apt:
    update_cache: yes
    upgrade: 'yes'
- name: 1.1 -- Install all required dependencies
  apt: name={{ item }} state=present
  with_items:
    - python3-pip
    - python3-dev
    - build-essential
    - libssl-dev
    - libffi-dev
    - apt-transport-https
    - ca-certificates
    - curl
    - unzip
    - software-properties-common

- name: 1.2 -- Download the awscli bundle.
  get_url: url=https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip dest=/tmp/awscliv2.zip
  register: aws_cli_download_bundle

- name: 1.3 -- Unarchive the installer.
  unarchive: src=/tmp/awscliv2.zip dest=/tmp copy=no
  # when: aws_cli_download_bundle.changed
  register: aws_cli_unarchive_installer

- name: 1.4 -- Install awscliv2.
  shell: bash /tmp/aws/install