---
  - hosts: all
    tasks:
      - name: 1.0 -- Check for hostname
        command: hostname
        register: hostname_out
        
      - debug:
          msg: "Server's hostname is: {{ hostname_out.stdout }}"