--- 
  - hosts: loadbalancer
    become: true
    tasks:
      - name:   verify nginx
        command: service nginx status

      - name: verify nginx is listening to port 80
        wait_for: port=80 timeout=1

  - hosts: webserver
    become: true
    tasks:
      - name:   verify apache2
        command: service apache2 status
      
      - name: verify apache2 is listening to port 80
        wait_for: port=80 timeout=1

  - hosts: database
    become: true
    tasks:
      - name:   verify nginx
        command: service mysql status

      - name: verify mysql is listening to port 80
        wait_for: port=3306 timeout=1

  - hosts: controller
    become: true
    tasks:  
      - name: Verify end-to-end respones
        uri: url=http://{{ item }} return_content=yes
        with_items: groups['loadbalancer']
        register: lb_index

      - fail: msg='index failed to return content'
        when: "'Hello, from von' not in item.content"
        with_items: "{{ lb_index['result'] }}"