---
  - hosts: loadbalancer
    become: true
    tasks: 
      - srevice: name=nginx state=stopped

  - hosts: webserver
    become: true
    tasks: 
      - service: name=apache2 state=stopped
    
  - hosts: database
    become: true
    tasks:  
      - service: name=mysql state=restartd

  - hosts: webserver
    become: true
    tasks:
      - service: name=apache2 state=started
  
  - hosts: loadbalancer
    become: true
    tasks: 
      - service: name=nginx state=started