---
  - hosts: webserver
    become: true
    tasks:
      - name: 1.0 -- Install apache2
        apt: name={{ item }} state=present update_cache=yes
        loop:
          - apache2
          - libapache2-mod-wsgi
          - python3-pip
          - python3-dev
          - python3-virtualenv
          - build-essential
          - libssl-dev
          - libffi-dev
      
